
$computers = "ANTHONYJAMES", "AP2017", "BBLITZ", "BFLOWERS", "BHARRIS", "BOBMURRAY", "BRADHERRON16", "CAROLVERRASTRO", "CARSONTHOMAS", "CHARLESROSS", "CHARLESSANDERS", "CIANNACONE", "CREISER", "CRYSTALBURNS", "DAVIDHOGGLE", "DCOLBURN", "DCOLLINS", "DELLBOYER", "DERICCLYCE", "DONALDSPAULDING", "DR-SUP-LT-02", "DR-SUP-PC-02", "DR-SUP-PC-06", "DWIDMANN", "ERICLOEFFLER", "ERICMCADAM", "ERNESTOMARQUEZ", "ESUMNER", "EVANSCHAACK", "GARETTBROWN", "GGUIDO", "GILLSAUM", "GPDELVECCHIO", "GUILLERMOSANDER", "GWELLS", "HELENGOUSSAROVA", "HL7-PROG-LT-02", "HL7-PROG-LT-08", "J719ORSINO", "JANMANISCALCO", "JARONICA", "JBAPTISTE", "JDECOSTER", "JDOWDALL", "JGRONBACH", "JLOMBARDO16", "JOANTOTH", "JODIELECOQUE", "JOHARIBARBER", "JOSEPHGALLUP", "JPELOSO", "JSOUTHEY", "JSTALCUP", "KDOERFERT", "KENNYMCKELVEY", "KINGRAHAM-PC", "KKARIO16", "KMHA-TEST1", "KWARD", "LAURENGIORDANO", "LISETTECARRARA", "LJENKINS", "LNR-44MX9G2", "LOANER-D74X9G2", "LORIWHEELER", "LUISTROYA", "MARODRIGUEZ", "MATTREPPA", "MAURICEJONES", "MAVRACH", "MICHELLEHOWE", "MIKEISHEE", "MMAALI", "MMOLINO", "MORRISGODEAUX", "MVARTANIAN16", "NERICKSON", "NICKKARAVITES", "NLENAR16", "NSENHAUSER16", "NVASQUEZMOTA", "OPS-VP-TAB-1", "PROD-LEAD-LT-02", "PURCH-LT-01", "RDIAZ", "REMCLI-4DRFKW2", "REMFSE-144TJW2", "REMFSE-1DRJT32", "REMFSE-1KT82H2", "REMFSE-2DRFKW2", "REMFSE-3L2HNH2", "REMFSE-JCRFKW2", "REMIMP-3DRFKW2", "REMIMP-444TJW2", "REMIMP-4W2M6Y2", "REMISS-31YT32", "REMLAT-CYWWYZ1", "REMSLS-1DRFKW2", "REMSLS-1FX82H2", "REMSLS-57Z9R72", "REMSLS-BCGM6Y2", "REMSLS-JXMM6Y2", "RMANNALORO", "RND-ENG-LT-01", "ROBERTKENLEY", "SALESOPS-LT-04", "SLOEHRKE", "SONIAENDERBY", "STEVENSIREIKA", "SUP-TECH-LT-03", "SUP-TECH-LT-04", "SUP-TECH-LT-10", "SUP-TECH-LT-11", "SUP-TECH-LT-15", "TCOLEMAN", "TIMKEARNS", "TODDHALL", "TPATEL", "TTHOMPSON", "VICTORMARONE", "VIZDEVLT02", "VIZDEVLT05", "WAREHOUSE-LT-01", "WAY-10RSQN2", "WAY-8D4QNH2", "WAYACC-244TJW2", "WAYACC-344TJW2", "WAYACC-B6NM6Y2", "WAYACC-HV6XM13", "WAYCCC-11MX9G2", "WAYCSS-C1PKT32", "WAYCSS-F8QQT32", "WAYEMT-P2G5JBBL", "WAYIMP-71DJT32", "WAYINT-1BWQT32", "WAYISS-1T3QNH2", "WAYISS-D9092H2", "WAYISS-J9YJT32", "WAYREP-2GRJT32", "YDENEGA16"

ForEach ($hostname in $computers) {

    try {
    $description = Get-ADComputer $hostname -Properties Description | select -ExpandProperty description
    }
    catch {
    $description = "No description"
    }
    if ( $description -eq $null) {
        echo "No description"
        }
    else {
        echo "$description"
        }

    }